FROM alpine:3.21.3

RUN apk add --no-cache curl

ENTRYPOINT [ "sh", "-c" ]

CMD [ "until curl -f -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token; do sleep 2; done; exit 0" ]
