FROM alpine:3.20.2

RUN apk add --no-cache curl

ENTRYPOINT [ "sh", "-c" ]

CMD [ "until curl -f -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token; do sleep 2s; done; curl -fsI -X POST http://localhost:15020/quitquitquit; exit 0" ]
